import Boundary
import Amalgamation
import Certificates
import Interfaces
import Recurrence
import Shell
import PathGraph
import Residual
import Graft
import Identification
import SpiderTheorem
import SecondRecurrence
import SecondShell
import SecondSpider
import ThirdRecurrence
import ThirdShell
import ThirdSpider
import VariableGadget
import VariableCore
import VariableInterval
import VariableIdentification
import VariableSpider
import FiniteAlphaTransfer
import CoreConcat
import FixedDepthSeeds
import Q18Gadget
import Q18Core
import Q18Interval
import EventualDepth
import AllOddSeeds
import AllOddDepth
import AllOddAsymptotic
import AllOddRootedGraft
import CompatibleSeeds
import CompatibleDepth
import CompatibleAsymptotic
import EvenResidual
import EvenIdentification
import EvenShell
import EvenTransfer
import AllLengthsDepth
import ReverseCore
import ReverseTracking
import ReverseSeeds
import ReverseDepth
import Q11Gadget
import Q11Core
import Q11Tracking
import Q11Recipes
import Q11Prefix
import Q11Depth
#check GracefulBoundary.Q11.gadget_inserted
#check GracefulBoundary.Q11.q11_preserves_invariant
#check GracefulBoundary.Q11.extend_tracks_maximum
#check GracefulBoundary.Q11.source_iterate
#check GracefulBoundary.Q11.recipe_coverage
#check GracefulBoundary.Q11.base_finite_cover
#check GracefulBoundary.Q11.bridge_finite_cover
#check GracefulBoundary.Q11.growing_core_interval
#check GracefulBoundary.Q11.all_lengths_prefix_zero
#check GracefulBoundary.Q11.all_lengths_eventual_zero
#check GracefulBoundary.Q11.prefix_dominates_D6
#check GracefulBoundary.Q11.cutoff_minimal
#check GracefulBoundary.Q11.prefix_monotone
#check GracefulBoundary.Q11.prefix_error_bound
#check GracefulBoundary.Q11.prefix_ratio_precision_limit
#print axioms GracefulBoundary.seed2_valid
#print axioms GracefulBoundary.seed3_valid
#print axioms GracefulBoundary.first_even_step_valid
#print axioms GracefulBoundary.first_odd_step_valid
#print axioms GracefulBoundary.bump_positive
#print axioms GracefulBoundary.old_positive_band
#print axioms GracefulBoundary.high_gadget
#print axioms GracefulBoundary.low_gadget
#print axioms GracefulBoundary.inserted_sums_exact
#print axioms GracefulBoundary.gadget_edges
#print axioms GracefulBoundary.retained_sum_range
#print axioms GracefulBoundary.recurrence_sum_partition
#print axioms GracefulBoundary.recurrence_sum_disjoint
#print axioms GracefulBoundary.shifted_sum_injective
#print axioms GracefulBoundary.shifted_edge_sum
#print axioms GracefulBoundary.next_anchor_index
#print axioms GracefulBoundary.next_last_value
#print axioms GracefulBoundary.induction_from_two_seeds
#print axioms GracefulBoundary.core_difference
#print axioms GracefulBoundary.core_difference_band
#print axioms GracefulBoundary.count_band
#print axioms GracefulBoundary.shell_differences_exact
#print axioms GracefulBoundary.alphaShift_injective
#print axioms GracefulBoundary.alphaShift_crossing
#print axioms GracefulBoundary.translate_difference
#print axioms GracefulBoundary.mixed_label_collision
#print axioms GracefulBoundary.amalgam_label_coverage
#print axioms GracefulBoundary.complement_difference
#print axioms GracefulBoundary.complement_max_zero
#print axioms GracefulBoundary.graftLabel_embed
#print axioms GracefulBoundary.graft_vertices
#print axioms GracefulBoundary.distance_comm
#print axioms GracefulBoundary.alphaShift_edge
#print axioms GracefulBoundary.graft_weight_left
#print axioms GracefulBoundary.graft_weight_right
#print axioms GracefulBoundary.graceful_graft
#print axioms GracefulBoundary.decode_core_sums
#print axioms GracefulBoundary.shell_plus_core_differences
#print axioms GracefulBoundary.seed2_full_path
#print axioms GracefulBoundary.seed3_full_path
#print axioms GracefulBoundary.graceful_complement
#print axioms GracefulBoundary.graft_zero_anchor
#print axioms GracefulBoundary.graft_max_anchor
#print axioms GracefulBoundary.uniform_cores_if_recurrence
#print axioms GracefulBoundary.extend_length
#print axioms GracefulBoundary.core_boundary_contract
#print axioms GracefulBoundary.residual_center_zero
#print axioms GracefulBoundary.spider_size_accounting
#print axioms GracefulBoundary.sides_cons
#print axioms GracefulBoundary.highs_cons
#print axioms GracefulBoundary.lows_cons
#print axioms GracefulBoundary.sides_append
#print axioms GracefulBoundary.sides_map
#print axioms GracefulBoundary.count_sides
#print axioms GracefulBoundary.core_zero_count
#print axioms GracefulBoundary.split_two
#print axioms GracefulBoundary.core_parts_positive
#print axioms GracefulBoundary.map_bump_of_positive
#print axioms GracefulBoundary.highs_append
#print axioms GracefulBoundary.lows_append
#print axioms GracefulBoundary.highs_map
#print axioms GracefulBoundary.lows_map
#print axioms GracefulBoundary.surgery_highs
#print axioms GracefulBoundary.surgery_lows
#print axioms GracefulBoundary.bump_range
#print axioms GracefulBoundary.side_interval_extension
#print axioms GracefulBoundary.extend_side_partitions
#print axioms GracefulBoundary.edgeSums_overlap
#print axioms GracefulBoundary.edgeSums_join
#print axioms GracefulBoundary.edgeSums_shift
#print axioms GracefulBoundary.surgery_sums
#print axioms GracefulBoundary.old_sums
#print axioms GracefulBoundary.remove_three_sum_values
#print axioms GracefulBoundary.shifted_rest_interval
#print axioms GracefulBoundary.enlarged_sum_interval
#print axioms GracefulBoundary.core_part_boundaries
#print axioms GracefulBoundary.extend_edge_partition
#print axioms GracefulBoundary.surgery_patch_index
#print axioms GracefulBoundary.extend_endpoints_anchors
#print axioms GracefulBoundary.recurrence_preserves_invariant
#print axioms GracefulBoundary.uniform_anchored_cores
#print axioms GracefulBoundary.decode_zipIdx
#print axioms GracefulBoundary.coreLabels_decode
#print axioms GracefulBoundary.decode_side_permutations
#print axioms GracefulBoundary.boundary_entries_small
#print axioms GracefulBoundary.decode_core_edge_values
#print axioms GracefulBoundary.reflected_range
#print axioms GracefulBoundary.decoded_core_labels
#print axioms GracefulBoundary.pairs_perm
#print axioms GracefulBoundary.opposite_pairs_labels
#print axioms GracefulBoundary.shell_labels_partition
#print axioms GracefulBoundary.complete_path_labels
#print axioms GracefulBoundary.coreLabels_lookup
#print axioms GracefulBoundary.coreLabels_length
#print axioms GracefulBoundary.decoded_core_boundaries
#print axioms GracefulBoundary.edgeDiffs_join
#print axioms GracefulBoundary.edgeDiffs_overlap
#print axioms GracefulBoundary.edgeDiffs_reverse
#print axioms GracefulBoundary.selected_arm_differences
#print axioms GracefulBoundary.pair_block_differences
#print axioms GracefulBoundary.opposite_arm_differences
#print axioms GracefulBoundary.full_path_edge_decomposition
#print axioms GracefulBoundary.complete_path_differences
#print axioms GracefulBoundary.cross_symm
#print axioms GracefulBoundary.crosses_prepend
#print axioms GracefulBoundary.crosses_join
#print axioms GracefulBoundary.crosses_reverse
#print axioms GracefulBoundary.crosses_overlap
#print axioms GracefulBoundary.decoded_core_crosses
#print axioms GracefulBoundary.selected_arm_crosses
#print axioms GracefulBoundary.pair_block_crosses
#print axioms GracefulBoundary.opposite_arm_crosses
#print axioms GracefulBoundary.complete_path_crosses
#print axioms GracefulBoundary.selected_arm_length
#print axioms GracefulBoundary.complete_path_midpoint
#print axioms GracefulBoundary.boundary_shell_bridge
#print axioms GracefulBoundary.complete_path_core_lookup
#print axioms GracefulBoundary.core_to_path_bridge
#print axioms GracefulBoundary.uniform_midpoint_alpha_paths
#print axioms GracefulBoundary.list_band_bijection
#print axioms GracefulBoundary.edgeDiffs_lookup
#print axioms GracefulBoundary.crosses_lookup
#print axioms GracefulBoundary.list_path_graceful
#print axioms GracefulBoundary.list_path_alpha
#print axioms GracefulBoundary.certificate_graph
#print axioms GracefulBoundary.certificate_graph_anchors
#print axioms GracefulBoundary.rectangle_band
#print axioms GracefulBoundary.band_precompose
#print axioms GracefulBoundary.mirror_mirror
#print axioms GracefulBoundary.vertexDecode_code
#print axioms GracefulBoundary.vertexCode_decode
#print axioms GracefulBoundary.residual_arm_code
#print axioms GracefulBoundary.residual_arm_band
#print axioms GracefulBoundary.residual_vertex_band
#print axioms GracefulBoundary.unfolded_folded
#print axioms GracefulBoundary.folded_unfolded
#print axioms GracefulBoundary.edgeDecode_code
#print axioms GracefulBoundary.edgeCode_decode
#print axioms GracefulBoundary.residual_arm_weight_code
#print axioms GracefulBoundary.residual_arm_edge_band
#print axioms GracefulBoundary.residual_leaf_weight
#print axioms GracefulBoundary.residual_edge_band
#print axioms GracefulBoundary.residual_gracefulness
#print axioms GracefulBoundary.certificate_graft
#print axioms GracefulBoundary.certificate_graft_anchors
#print axioms GracefulBoundary.uniform_boundary_grafts
#print axioms GracefulBoundary.graceful_transport
#print axioms GracefulBoundary.graftToSpider_left
#print axioms GracefulBoundary.graftToSpider_right
#print axioms GracefulBoundary.graft_spider_left_inverse
#print axioms GracefulBoundary.graft_spider_right_inverse
#print axioms GracefulBoundary.edge_graft_spider_left_inverse
#print axioms GracefulBoundary.edge_graft_spider_right_inverse
#print axioms GracefulBoundary.embed_left
#print axioms GracefulBoundary.embed_right
#print axioms GracefulBoundary.graft_spider_weights
#print axioms GracefulBoundary.graft_graceful_on_spider
#print axioms GracefulBoundary.zero_anchor_identification
#print axioms GracefulBoundary.maximum_anchor_identification
#print axioms GracefulBoundary.uniform_first_arm_spiders
#print axioms GracefulBoundary.swapIndex_first
#print axioms GracefulBoundary.swapIndex_second
#print axioms GracefulBoundary.swapIndex_involution
#print axioms GracefulBoundary.swapVertex_involution
#print axioms GracefulBoundary.swapEdge_involution
#print axioms GracefulBoundary.swap_weights
#print axioms GracefulBoundary.graceful_swap
#print axioms GracefulBoundary.uniform_selected_arm_anchors
#print axioms GracefulBoundary.first_pair_prescribed_zero
#print axioms GracefulBoundary.first_pair_at_depth
#print axioms GracefulBoundary.SecondPair.seed2_valid
#print axioms GracefulBoundary.SecondPair.seed3_valid
#print axioms GracefulBoundary.SecondPair.seed4_valid
#print axioms GracefulBoundary.SecondPair.seed5_valid
#print axioms GracefulBoundary.SecondPair.extend_length
#print axioms GracefulBoundary.SecondPair.core_zero_count
#print axioms GracefulBoundary.SecondPair.core_parts_positive
#print axioms GracefulBoundary.SecondPair.extend_side_partitions
#print axioms GracefulBoundary.SecondPair.core_part_boundaries
#print axioms GracefulBoundary.SecondPair.extend_edge_partition
#print axioms GracefulBoundary.SecondPair.extend_endpoints_anchors
#print axioms GracefulBoundary.SecondPair.recurrence_preserves_invariant
#print axioms GracefulBoundary.SecondPair.strong_core_is_anchored
#print axioms GracefulBoundary.SecondPair.uniform_strong_cores
#print axioms GracefulBoundary.SecondPair.uniform_anchored_cores
#print axioms GracefulBoundary.SecondPair.exceptional_neighbours
#print axioms GracefulBoundary.SecondPair.rejects_recurrence_from_seed2
#print axioms GracefulBoundary.SecondPair.rejects_recurrence_from_seed3
#print axioms GracefulBoundary.SecondPair.core_to_path_bridge
#print axioms GracefulBoundary.SecondPair.uniform_midpoint_alpha_paths
#print axioms GracefulBoundary.SecondPair.certificate_graph
#print axioms GracefulBoundary.SecondPair.certificate_graph_anchors
#print axioms GracefulBoundary.SecondPair.certificate_graft
#print axioms GracefulBoundary.SecondPair.certificate_graft_anchors
#print axioms GracefulBoundary.SecondPair.uniform_boundary_grafts
#print axioms GracefulBoundary.SecondPair.zero_anchor_identification
#print axioms GracefulBoundary.SecondPair.maximum_anchor_identification
#print axioms GracefulBoundary.SecondPair.uniform_first_arm_spiders
#print axioms GracefulBoundary.SecondPair.uniform_selected_arm_anchors
#print axioms GracefulBoundary.SecondPair.second_pair_prescribed_zero
#print axioms GracefulBoundary.SecondPair.second_pair_at_depth
#print axioms GracefulBoundary.four_depths_prescribed_zero
#print axioms GracefulBoundary.ThirdPair.seed3_valid
#print axioms GracefulBoundary.ThirdPair.seed4_valid
#print axioms GracefulBoundary.ThirdPair.seed5_valid
#print axioms GracefulBoundary.ThirdPair.seed6_valid
#print axioms GracefulBoundary.ThirdPair.extend_length
#print axioms GracefulBoundary.ThirdPair.core_zero_count
#print axioms GracefulBoundary.ThirdPair.core_parts_positive
#print axioms GracefulBoundary.ThirdPair.extend_side_partitions
#print axioms GracefulBoundary.ThirdPair.core_part_boundaries
#print axioms GracefulBoundary.ThirdPair.extend_edge_partition
#print axioms GracefulBoundary.ThirdPair.extend_endpoints_anchors
#print axioms GracefulBoundary.ThirdPair.recurrence_preserves_invariant
#print axioms GracefulBoundary.ThirdPair.strong_core_is_anchored
#print axioms GracefulBoundary.ThirdPair.uniform_strong_cores
#print axioms GracefulBoundary.ThirdPair.uniform_anchored_cores
#print axioms GracefulBoundary.ThirdPair.weak_seed4_surgery_valid
#print axioms GracefulBoundary.ThirdPair.direct2_valid
#print axioms GracefulBoundary.ThirdPair.complete_path_endpoints
#print axioms GracefulBoundary.ThirdPair.core_to_path_bridge
#print axioms GracefulBoundary.ThirdPair.uniform_midpoint_alpha_paths
#print axioms GracefulBoundary.ThirdPair.certificate_graph
#print axioms GracefulBoundary.ThirdPair.certificate_graph_anchors
#print axioms GracefulBoundary.ThirdPair.certificate_graph_endpoints
#print axioms GracefulBoundary.ThirdPair.certificate_graft
#print axioms GracefulBoundary.ThirdPair.certificate_graft_anchors
#print axioms GracefulBoundary.ThirdPair.uniform_boundary_grafts
#print axioms GracefulBoundary.ThirdPair.zero_anchor_identification
#print axioms GracefulBoundary.ThirdPair.maximum_anchor_identification
#print axioms GracefulBoundary.ThirdPair.uniform_first_arm_spiders
#print axioms GracefulBoundary.ThirdPair.uniform_selected_arm_anchors
#print axioms GracefulBoundary.ThirdPair.third_pair_prescribed_zero
#print axioms GracefulBoundary.ThirdPair.third_pair_at_depth
#print axioms GracefulBoundary.six_depths_prescribed_zero
#print axioms GracefulBoundary.Variable.gadget_inserted
#print axioms GracefulBoundary.Variable.gadget_lengths
#print axioms GracefulBoundary.Variable.gadget_boundaries
#print axioms GracefulBoundary.Variable.surgery_highs
#print axioms GracefulBoundary.Variable.surgery_lows
#print axioms GracefulBoundary.Variable.bump9_positive
#print axioms GracefulBoundary.Variable.map_bump9_positive
#print axioms GracefulBoundary.Variable.edgeSums_shift9
#print axioms GracefulBoundary.Variable.edgeSums_right_head
#print axioms GracefulBoundary.Variable.edgeSums_left_last
#print axioms GracefulBoundary.Variable.middle_edges
#print axioms GracefulBoundary.Variable.surgery_sums
#print axioms GracefulBoundary.Variable.bump_range
#print axioms GracefulBoundary.Variable.side_interval_extension
#print axioms GracefulBoundary.Variable.decomposition
#print axioms GracefulBoundary.Variable.part_length
#print axioms GracefulBoundary.Variable.parts_positive
#print axioms GracefulBoundary.Variable.part_boundaries
#print axioms GracefulBoundary.Variable.extend_sides
#print axioms GracefulBoundary.Variable.shifted_rest_interval
#print axioms GracefulBoundary.Variable.enlarged_sum_interval
#print axioms GracefulBoundary.Variable.extend_sums
#print axioms GracefulBoundary.Variable.extend_length
#print axioms GracefulBoundary.Variable.surgery_patch_index
#print axioms GracefulBoundary.Variable.gadget_patch
#print axioms GracefulBoundary.Variable.extend_endpoints
#print axioms GracefulBoundary.Variable.extend_patch
#print axioms GracefulBoundary.Variable.q9_preserves_invariant
#print axioms GracefulBoundary.Variable.gadget_for_increment
#print axioms GracefulBoundary.Variable.interval_cores
#print axioms GracefulBoundary.Variable.interval_depth_pair
#print axioms GracefulBoundary.Variable.seedA2_valid
#print axioms GracefulBoundary.Variable.seedA3_valid
#print axioms GracefulBoundary.Variable.seedA4_valid
#print axioms GracefulBoundary.Variable.seedB8_valid
#print axioms GracefulBoundary.Variable.seedB9_valid
#print axioms GracefulBoundary.Variable.seedB10_valid
#print axioms GracefulBoundary.Variable.seedB11_valid
#print axioms GracefulBoundary.Variable.seedB12_valid
#print axioms GracefulBoundary.Variable.seedB13_valid
#print axioms GracefulBoundary.Variable.seedB14_valid
#print axioms GracefulBoundary.Variable.seedB15_valid
#print axioms GracefulBoundary.Variable.seedB16_valid
#print axioms GracefulBoundary.Variable.seedsA
#print axioms GracefulBoundary.Variable.seedsB
#print axioms GracefulBoundary.Variable.theoremA_cores
#print axioms GracefulBoundary.Variable.theoremB_cores
#print axioms GracefulBoundary.Variable.graftToSpider_left
#print axioms GracefulBoundary.Variable.graftToSpider_right
#print axioms GracefulBoundary.Variable.graft_spider_left_inverse
#print axioms GracefulBoundary.Variable.graft_spider_right_inverse
#print axioms GracefulBoundary.Variable.edge_graft_spider_left_inverse
#print axioms GracefulBoundary.Variable.edge_graft_spider_right_inverse
#print axioms GracefulBoundary.Variable.embed_left
#print axioms GracefulBoundary.Variable.embed_right
#print axioms GracefulBoundary.Variable.graft_spider_weights
#print axioms GracefulBoundary.Variable.graft_graceful_on_spider
#print axioms GracefulBoundary.Variable.core_to_path
#print axioms GracefulBoundary.Variable.certificate_graph
#print axioms GracefulBoundary.Variable.certificate_graph_anchors
#print axioms GracefulBoundary.Variable.certificate_graft
#print axioms GracefulBoundary.Variable.certificate_graft_anchors
#print axioms GracefulBoundary.Variable.zero_anchor_identification
#print axioms GracefulBoundary.Variable.maximum_anchor_identification
#print axioms GracefulBoundary.Variable.core_first_arm_spiders
#print axioms GracefulBoundary.Variable.core_selected_arm
#print axioms GracefulBoundary.Variable.core_prescribed_zero
#print axioms GracefulBoundary.Variable.theoremA_prescribed_zero
#print axioms GracefulBoundary.Variable.theoremB_prescribed_zero
#print axioms GracefulBoundary.Variable.complete_path_endpoint_labels
#print axioms GracefulBoundary.Variable.theoremA_interval_length
#print axioms GracefulBoundary.Variable.theoremB_interval_length
#print axioms GracefulBoundary.Variable.theoremB_odd_arm_length
#print axioms GracefulBoundary.FiniteAlpha.first_arm
#print axioms GracefulBoundary.FiniteAlpha.prescribed_zero
#print axioms GracefulBoundary.FixedDepth.side_interval
#print axioms GracefulBoundary.FixedDepth.sum_interval
#print axioms GracefulBoundary.FixedDepth.edgeSums_add
#print axioms GracefulBoundary.FixedDepth.edgeSums_append_known
#print axioms GracefulBoundary.FixedDepth.append_boundary_core
#print axioms GracefulBoundary.FixedDepth.append_pair
#print axioms GracefulBoundary.FixedDepth.core_pair_to_certificate
#print axioms GracefulBoundary.FixedDepth.core_pair_spider_transfer
#print axioms GracefulBoundary.FixedDepth.B6_2_valid
#print axioms GracefulBoundary.FixedDepth.B6_3_valid
#print axioms GracefulBoundary.FixedDepth.B6_4_valid
#print axioms GracefulBoundary.FixedDepth.B6_5_valid
#print axioms GracefulBoundary.FixedDepth.B6_6_valid
#print axioms GracefulBoundary.FixedDepth.B6_7_valid
#print axioms GracefulBoundary.FixedDepth.B6_8_valid
#print axioms GracefulBoundary.FixedDepth.B6_10_valid
#print axioms GracefulBoundary.FixedDepth.B9_2_valid
#print axioms GracefulBoundary.FixedDepth.B9_3_valid
#print axioms GracefulBoundary.FixedDepth.B9_4_valid
#print axioms GracefulBoundary.FixedDepth.B9_5_valid
#print axioms GracefulBoundary.FixedDepth.B9_6_valid
#print axioms GracefulBoundary.FixedDepth.B9_7_valid
#print axioms GracefulBoundary.FixedDepth.B9_8_valid
#print axioms GracefulBoundary.FixedDepth.B9_10_valid
#print axioms GracefulBoundary.FixedDepth.repeatedBlock_boundary
#print axioms GracefulBoundary.FixedDepth.seed_pair_for_depth
#print axioms GracefulBoundary.Variable.Q18.gadget_inserted
#print axioms GracefulBoundary.Variable.Q18.gadget_lengths
#print axioms GracefulBoundary.Variable.Q18.gadget_boundaries
#print axioms GracefulBoundary.Variable.Q18.surgery_highs
#print axioms GracefulBoundary.Variable.Q18.surgery_lows
#print axioms GracefulBoundary.Variable.Q18.bump18_positive
#print axioms GracefulBoundary.Variable.Q18.map_bump18_positive
#print axioms GracefulBoundary.Variable.Q18.edgeSums_shift18
#print axioms GracefulBoundary.Variable.Q18.edgeSums_right_head
#print axioms GracefulBoundary.Variable.Q18.edgeSums_left_last
#print axioms GracefulBoundary.Variable.Q18.middle_edges
#print axioms GracefulBoundary.Variable.Q18.surgery_sums
#print axioms GracefulBoundary.Variable.Q18.bump_range
#print axioms GracefulBoundary.Variable.Q18.side_interval_extension
#print axioms GracefulBoundary.Variable.Q18.extend_sides
#print axioms GracefulBoundary.Variable.Q18.shifted_rest_interval
#print axioms GracefulBoundary.Variable.Q18.enlarged_sum_interval
#print axioms GracefulBoundary.Variable.Q18.extend_sums
#print axioms GracefulBoundary.Variable.Q18.extend_length
#print axioms GracefulBoundary.Variable.Q18.surgery_patch_index
#print axioms GracefulBoundary.Variable.Q18.gadget_patch
#print axioms GracefulBoundary.Variable.Q18.extend_endpoints
#print axioms GracefulBoundary.Variable.Q18.extend_patch
#print axioms GracefulBoundary.Variable.Q18.q18_preserves_invariant
#print axioms GracefulBoundary.Variable.Q18.paired_step
#print axioms GracefulBoundary.Variable.Q18.paired_interval
#print axioms GracefulBoundary.Variable.Q18.interval_cores_plus
#print axioms GracefulBoundary.Variable.Q18.interval_depth_pair_plus
#print axioms GracefulBoundary.Variable.Q18.theoremA_plus_cores
#print axioms GracefulBoundary.Variable.Q18.theoremB_plus_cores
#print axioms GracefulBoundary.Eventual.anchored_to_pair
#print axioms GracefulBoundary.Eventual.b_plus_coverage
#print axioms GracefulBoundary.Eventual.coverage_step
#print axioms GracefulBoundary.Eventual.overlap_windows
#print axioms GracefulBoundary.Eventual.consecutive_closure
#print axioms GracefulBoundary.Eventual.eventual_coverage
#print axioms GracefulBoundary.Eventual.eventual_depth_bound
#print axioms GracefulBoundary.Eventual.eventual_fixed_depth_zero
#print axioms GracefulBoundary.AllOdd.B8_2_valid
#print axioms GracefulBoundary.AllOdd.B8_4_valid
#print axioms GracefulBoundary.AllOdd.B8_6_valid
#print axioms GracefulBoundary.AllOdd.B8_8_valid
#print axioms GracefulBoundary.AllOdd.B8_10_valid
#print axioms GracefulBoundary.AllOdd.B9_2_valid
#print axioms GracefulBoundary.AllOdd.B9_4_valid
#print axioms GracefulBoundary.AllOdd.B9_6_valid
#print axioms GracefulBoundary.AllOdd.B9_8_valid
#print axioms GracefulBoundary.AllOdd.B9_10_valid
#print axioms GracefulBoundary.AllOdd.B10_2_valid
#print axioms GracefulBoundary.AllOdd.B10_4_valid
#print axioms GracefulBoundary.AllOdd.B10_6_valid
#print axioms GracefulBoundary.AllOdd.B10_8_valid
#print axioms GracefulBoundary.AllOdd.B10_10_valid
#print axioms GracefulBoundary.AllOdd.B11_2_valid
#print axioms GracefulBoundary.AllOdd.B11_4_valid
#print axioms GracefulBoundary.AllOdd.B11_6_valid
#print axioms GracefulBoundary.AllOdd.B11_8_valid
#print axioms GracefulBoundary.AllOdd.B11_10_valid
#print axioms GracefulBoundary.AllOdd.B12_2_valid
#print axioms GracefulBoundary.AllOdd.B12_4_valid
#print axioms GracefulBoundary.AllOdd.B12_6_valid
#print axioms GracefulBoundary.AllOdd.B12_8_valid
#print axioms GracefulBoundary.AllOdd.B12_10_valid
#print axioms GracefulBoundary.AllOdd.B13_2_valid
#print axioms GracefulBoundary.AllOdd.B13_4_valid
#print axioms GracefulBoundary.AllOdd.B13_6_valid
#print axioms GracefulBoundary.AllOdd.B13_8_valid
#print axioms GracefulBoundary.AllOdd.B13_10_valid
#print axioms GracefulBoundary.AllOdd.small_seed
#print axioms GracefulBoundary.AllOdd.steps_spec
#print axioms GracefulBoundary.AllOdd.upper_monotone
#print axioms GracefulBoundary.AllOdd.steps_minimal
#print axioms GracefulBoundary.AllOdd.coverage_append
#print axioms GracefulBoundary.AllOdd.coverage_grow
#print axioms GracefulBoundary.AllOdd.residue_selection
#print axioms GracefulBoundary.AllOdd.coverage_from_interval
#print axioms GracefulBoundary.AllOdd.coverage_small
#print axioms GracefulBoundary.AllOdd.coverage_large
#print axioms GracefulBoundary.AllOdd.cutoff_ge_nineteen
#print axioms GracefulBoundary.AllOdd.cutoff_depth_bound
#print axioms GracefulBoundary.AllOdd.odd_coverage
#print axioms GracefulBoundary.AllOdd.odd_pair_certificate
#print axioms GracefulBoundary.AllOdd.all_odd_eventual_zero
#print axioms GracefulBoundary.AllOdd.prefix_threshold
#print axioms GracefulBoundary.AllOdd.prefix_inside
#print axioms GracefulBoundary.AllOdd.all_odd_prefix_zero
#print axioms GracefulBoundary.AllOdd.core_size_units
#print axioms GracefulBoundary.AllOdd.prefix_error_bound
#print axioms GracefulBoundary.AllOdd.prefix_ratio_precision_limit
#print axioms GracefulBoundary.AllOdd.rooted_path_accounting
#print axioms GracefulBoundary.AllOdd.certificate_rooted_zero
#print axioms GracefulBoundary.AllOdd.all_odd_rooted_zero
#print axioms GracefulBoundary.Compatible.C16_12_valid
#print axioms GracefulBoundary.Compatible.C16_14_valid
#print axioms GracefulBoundary.Compatible.C16_16_valid
#print axioms GracefulBoundary.Compatible.C16_18_valid
#print axioms GracefulBoundary.Compatible.C16_20_valid
#print axioms GracefulBoundary.Compatible.C16_22_valid
#print axioms GracefulBoundary.Compatible.C16_24_valid
#print axioms GracefulBoundary.Compatible.C16_26_valid
#print axioms GracefulBoundary.Compatible.C17_12_valid
#print axioms GracefulBoundary.Compatible.C17_14_valid
#print axioms GracefulBoundary.Compatible.C17_16_valid
#print axioms GracefulBoundary.Compatible.C17_18_valid
#print axioms GracefulBoundary.Compatible.C17_20_valid
#print axioms GracefulBoundary.Compatible.C17_22_valid
#print axioms GracefulBoundary.Compatible.C17_24_valid
#print axioms GracefulBoundary.Compatible.C17_26_valid
#print axioms GracefulBoundary.Compatible.C18_12_valid
#print axioms GracefulBoundary.Compatible.C18_14_valid
#print axioms GracefulBoundary.Compatible.C18_16_valid
#print axioms GracefulBoundary.Compatible.C18_18_valid
#print axioms GracefulBoundary.Compatible.C18_20_valid
#print axioms GracefulBoundary.Compatible.C18_22_valid
#print axioms GracefulBoundary.Compatible.C18_24_valid
#print axioms GracefulBoundary.Compatible.C18_26_valid
#print axioms GracefulBoundary.Compatible.C19_12_valid
#print axioms GracefulBoundary.Compatible.C19_14_valid
#print axioms GracefulBoundary.Compatible.C19_16_valid
#print axioms GracefulBoundary.Compatible.C19_18_valid
#print axioms GracefulBoundary.Compatible.C19_20_valid
#print axioms GracefulBoundary.Compatible.C19_22_valid
#print axioms GracefulBoundary.Compatible.C19_24_valid
#print axioms GracefulBoundary.Compatible.C19_26_valid
#print axioms GracefulBoundary.Compatible.C20_12_valid
#print axioms GracefulBoundary.Compatible.C20_14_valid
#print axioms GracefulBoundary.Compatible.C20_16_valid
#print axioms GracefulBoundary.Compatible.C20_18_valid
#print axioms GracefulBoundary.Compatible.C20_20_valid
#print axioms GracefulBoundary.Compatible.C20_22_valid
#print axioms GracefulBoundary.Compatible.C20_24_valid
#print axioms GracefulBoundary.Compatible.C20_26_valid
#print axioms GracefulBoundary.Compatible.C21_12_valid
#print axioms GracefulBoundary.Compatible.C21_14_valid
#print axioms GracefulBoundary.Compatible.C21_16_valid
#print axioms GracefulBoundary.Compatible.C21_18_valid
#print axioms GracefulBoundary.Compatible.C21_20_valid
#print axioms GracefulBoundary.Compatible.C21_22_valid
#print axioms GracefulBoundary.Compatible.C21_24_valid
#print axioms GracefulBoundary.Compatible.C21_26_valid
#print axioms GracefulBoundary.Compatible.compatible_seed
#print axioms GracefulBoundary.Compatible.steps_spec
#print axioms GracefulBoundary.Compatible.upper_monotone
#print axioms GracefulBoundary.Compatible.steps_minimal
#print axioms GracefulBoundary.Compatible.seed_interval_selection
#print axioms GracefulBoundary.Compatible.residue_selection
#print axioms GracefulBoundary.Compatible.coverage_from_interval
#print axioms GracefulBoundary.Compatible.coverage_large
#print axioms GracefulBoundary.Compatible.cutoff_ge_nineteen
#print axioms GracefulBoundary.Compatible.cutoff_depth_bound
#print axioms GracefulBoundary.Compatible.odd_coverage
#print axioms GracefulBoundary.Compatible.all_odd_eventual_zero
#print axioms GracefulBoundary.Compatible.prefix_threshold
#print axioms GracefulBoundary.Compatible.prefix_inside
#print axioms GracefulBoundary.Compatible.all_odd_prefix_zero
#print axioms GracefulBoundary.Compatible.prefix_error_bound
#print axioms GracefulBoundary.Compatible.prefix_ratio_precision_limit
#print axioms GracefulBoundary.EvenResidual.rectangle_band
#print axioms GracefulBoundary.EvenResidual.band_precompose
#print axioms GracefulBoundary.EvenResidual.mirror_mirror
#print axioms GracefulBoundary.EvenResidual.vertexDecode_code
#print axioms GracefulBoundary.EvenResidual.vertexCode_decode
#print axioms GracefulBoundary.EvenResidual.residual_arm_code
#print axioms GracefulBoundary.EvenResidual.residual_arm_band
#print axioms GracefulBoundary.EvenResidual.residual_vertex_band
#print axioms GracefulBoundary.EvenResidual.unfolded_folded
#print axioms GracefulBoundary.EvenResidual.folded_unfolded
#print axioms GracefulBoundary.EvenResidual.edgeDecode_code
#print axioms GracefulBoundary.EvenResidual.edgeCode_decode
#print axioms GracefulBoundary.EvenResidual.residual_arm_weight_code
#print axioms GracefulBoundary.EvenResidual.residual_arm_edge_band
#print axioms GracefulBoundary.EvenResidual.residual_leaf_weight
#print axioms GracefulBoundary.EvenResidual.residual_edge_band
#print axioms GracefulBoundary.EvenResidual.residual_gracefulness
#print axioms GracefulBoundary.Even.graftToSpider_left
#print axioms GracefulBoundary.Even.graftToSpider_right
#print axioms GracefulBoundary.Even.graft_spider_left_inverse
#print axioms GracefulBoundary.Even.graft_spider_right_inverse
#print axioms GracefulBoundary.Even.edge_graft_spider_left_inverse
#print axioms GracefulBoundary.Even.edge_graft_spider_right_inverse
#print axioms GracefulBoundary.Even.embed_left
#print axioms GracefulBoundary.Even.embed_right
#print axioms GracefulBoundary.Even.graft_spider_weights
#print axioms GracefulBoundary.Even.graft_graceful_on_spider
#print axioms GracefulBoundary.Even.core_difference
#print axioms GracefulBoundary.Even.decode_core_edge_values
#print axioms GracefulBoundary.Even.reflected_range
#print axioms GracefulBoundary.Even.decoded_core_labels
#print axioms GracefulBoundary.Even.opposite_pairs_labels
#print axioms GracefulBoundary.Even.shell_labels_partition
#print axioms GracefulBoundary.Even.complete_path_labels
#print axioms GracefulBoundary.Even.decoded_core_boundaries
#print axioms GracefulBoundary.Even.selected_arm_differences
#print axioms GracefulBoundary.Even.pair_block_differences
#print axioms GracefulBoundary.Even.opposite_arm_differences
#print axioms GracefulBoundary.Even.full_path_edge_decomposition
#print axioms GracefulBoundary.Even.reflected_sums
#print axioms GracefulBoundary.Even.complete_path_differences
#print axioms GracefulBoundary.Even.decoded_core_crosses
#print axioms GracefulBoundary.Even.selected_arm_crosses
#print axioms GracefulBoundary.Even.pair_block_crosses
#print axioms GracefulBoundary.Even.opposite_arm_crosses
#print axioms GracefulBoundary.Even.complete_path_crosses
#print axioms GracefulBoundary.Even.selected_arm_length
#print axioms GracefulBoundary.Even.complete_path_midpoint
#print axioms GracefulBoundary.Even.boundary_shell_bridge
#print axioms GracefulBoundary.Even.complete_path_core_lookup
#print axioms GracefulBoundary.Even.first_arm
#print axioms GracefulBoundary.Even.prescribed_zero
#print axioms GracefulBoundary.Even.core_pair_to_certificate
#print axioms GracefulBoundary.Even.core_pair_spider_transfer
#print axioms GracefulBoundary.AllLengths.even_coverage
#print axioms GracefulBoundary.AllLengths.all_even_eventual_zero
#print axioms GracefulBoundary.AllLengths.all_lengths_eventual_zero
#print axioms GracefulBoundary.AllLengths.all_lengths_prefix_zero
#print axioms GracefulBoundary.AllLengths.prefix_inside
#print axioms GracefulBoundary.AllLengths.cutoff_depth_bound
#print axioms GracefulBoundary.AllLengths.prefix_error_bound
#print axioms GracefulBoundary.AllLengths.prefix_ratio_precision_limit
#print axioms GracefulBoundary.ReverseComplement.sides_reverse
#print axioms GracefulBoundary.ReverseComplement.edgeSums_reverse
#print axioms GracefulBoundary.ReverseComplement.reflect_range
#print axioms GracefulBoundary.ReverseComplement.complement_sums
#print axioms GracefulBoundary.ReverseComplement.transform_boundary
#print axioms GracefulBoundary.ReverseComplement.transform_involution
#print axioms GracefulBoundary.ReverseComplement.transform_lookup
#print axioms GracefulBoundary.ReverseComplement.adjacent_zeros_coverage
#print axioms GracefulBoundary.ReverseComplement.extend_prefix_lookup
#print axioms GracefulBoundary.ReverseComplement.extend_tracks_maximum
#print axioms GracefulBoundary.ReverseComplement.source_step_four
#print axioms GracefulBoundary.ReverseComplement.source_step_six
#print axioms GracefulBoundary.ReverseComplement.source_interval
#print axioms GracefulBoundary.ReverseComplement.source_reflects_to_coverage
#print axioms GracefulBoundary.ReverseComplement.interval_depth_selection
#print axioms GracefulBoundary.ReverseComplement.source_interval_coverage
#print axioms GracefulBoundary.ReverseComplement.selected_gadget_signatures
#print axioms GracefulBoundary.ReverseComplement.seed16_tracks
#print axioms GracefulBoundary.ReverseComplement.seed17_tracks
#print axioms GracefulBoundary.ReverseComplement.seed18_tracks
#print axioms GracefulBoundary.ReverseComplement.seed19_tracks
#print axioms GracefulBoundary.ReverseComplement.seed20_tracks
#print axioms GracefulBoundary.ReverseComplement.seed21_tracks
#print axioms GracefulBoundary.ReverseComplement.residue_seed
#print axioms GracefulBoundary.ReverseComplement.common_residue_interval
#print axioms GracefulBoundary.ReverseComplement.core_prefix_coverage
#print axioms GracefulBoundary.ReverseComplement.odd_prefix_identity
#print axioms GracefulBoundary.ReverseComplement.even_prefix_identity
#print axioms GracefulBoundary.ReverseComplement.odd_prescribed_zero
#print axioms GracefulBoundary.ReverseComplement.even_prescribed_zero
#print axioms GracefulBoundary.ReverseComplement.all_lengths_prefix_zero
#print axioms GracefulBoundary.ReverseComplement.steps_spec
#print axioms GracefulBoundary.ReverseComplement.steps_minimal
#print axioms GracefulBoundary.ReverseComplement.cutoff_ge_nineteen
#print axioms GracefulBoundary.ReverseComplement.cutoff_covers
#print axioms GracefulBoundary.ReverseComplement.all_lengths_eventual_zero
#print axioms GracefulBoundary.ReverseComplement.prefix_error_bound
#print axioms GracefulBoundary.ReverseComplement.prefix_inside
#print axioms GracefulBoundary.ReverseComplement.cutoff_depth_bound
#print axioms GracefulBoundary.ReverseComplement.prefix_dominates_D5
#print axioms GracefulBoundary.ReverseComplement.prefix_ratio_precision_limit
#print axioms GracefulBoundary.Q11.gadget_inserted
#print axioms GracefulBoundary.Q11.gadget_lengths
#print axioms GracefulBoundary.Q11.gadget_boundaries
#print axioms GracefulBoundary.Q11.surgery_highs
#print axioms GracefulBoundary.Q11.surgery_lows
#print axioms GracefulBoundary.Q11.bump11_positive
#print axioms GracefulBoundary.Q11.map_bump11_positive
#print axioms GracefulBoundary.Q11.edgeSums_shift11
#print axioms GracefulBoundary.Q11.edgeSums_right_head
#print axioms GracefulBoundary.Q11.edgeSums_left_last
#print axioms GracefulBoundary.Q11.middle_edges
#print axioms GracefulBoundary.Q11.surgery_sums
#print axioms GracefulBoundary.Q11.bump_range
#print axioms GracefulBoundary.Q11.side_interval_extension
#print axioms GracefulBoundary.Q11.decomposition
#print axioms GracefulBoundary.Q11.part_length
#print axioms GracefulBoundary.Q11.parts_positive
#print axioms GracefulBoundary.Q11.part_boundaries
#print axioms GracefulBoundary.Q11.extend_sides
#print axioms GracefulBoundary.Q11.shifted_rest_interval
#print axioms GracefulBoundary.Q11.enlarged_sum_interval
#print axioms GracefulBoundary.Q11.extend_sums
#print axioms GracefulBoundary.Q11.extend_length
#print axioms GracefulBoundary.Q11.surgery_patch_index
#print axioms GracefulBoundary.Q11.gadget_patch
#print axioms GracefulBoundary.Q11.extend_endpoints
#print axioms GracefulBoundary.Q11.extend_patch
#print axioms GracefulBoundary.Q11.q11_preserves_invariant
#print axioms GracefulBoundary.Q11.extend_prefix_lookup
#print axioms GracefulBoundary.Q11.extend_tracks_maximum
#print axioms GracefulBoundary.Q11.source_step
#print axioms GracefulBoundary.Q11.source_iterate
#print axioms GracefulBoundary.Q11.exact_seed
#print axioms GracefulBoundary.Q11.recipe_coverage
#print axioms GracefulBoundary.Q11.finite_cover_recipe
#print axioms GracefulBoundary.Q11.finite_cover_coverage
#print axioms GracefulBoundary.Q11.base_finite_cover
#print axioms GracefulBoundary.Q11.bridge_finite_cover
#print axioms GracefulBoundary.Q11.F_shift
#print axioms GracefulBoundary.Q11.valid_lift
#print axioms GracefulBoundary.Q11.bridge_coverage
#print axioms GracefulBoundary.Q11.base_core_coverage
#print axioms GracefulBoundary.Q11.growing_core_interval
#print axioms GracefulBoundary.Q11.all_depth_core_coverage
#print axioms GracefulBoundary.Q11.nonregression_finite
#print axioms GracefulBoundary.Q11.old_shift
#print axioms GracefulBoundary.Q11.F_dominates_D6
#print axioms GracefulBoundary.Q11.coverage_spider
#print axioms GracefulBoundary.Q11.all_lengths_prefix_zero
#print axioms GracefulBoundary.Q11.prefix_error_bound
#print axioms GracefulBoundary.Q11.prefix_inside
#print axioms GracefulBoundary.Q11.prefix_dominates_D6
#print axioms GracefulBoundary.Q11.F_monotone
#print axioms GracefulBoundary.Q11.prefix_monotone
#print axioms GracefulBoundary.Q11.cutoff_ge_nineteen
#print axioms GracefulBoundary.Q11.large_cutoff_spec
#print axioms GracefulBoundary.Q11.cutoff_covers
#print axioms GracefulBoundary.Q11.cutoff_previous_fails
#print axioms GracefulBoundary.Q11.cutoff_minimal
#print axioms GracefulBoundary.Q11.all_lengths_eventual_zero
#print axioms GracefulBoundary.Q11.cutoff_depth_bound
#print axioms GracefulBoundary.Q11.prefix_ratio_precision_limit
